### ISSUE TITLE
I think there is no need to explain here. 

### ISSUE THREAD

**Issue by Tamago4a** [arithfeather-scp-sl/PlayerUnstuck#1]
How can you upload a plugin with broadcast, the recent ability to customize it?
![текст поменять](https://user-images.githubusercontent.com/47304666/89449453-c4b1af00-d761-11ea-9e5d-ee7f795488a1.png)

**Comment by Tamago4a** [comment]
The mistake is that you publish the plugin, but do not allow people to change the text. I have a Russian server. Why do I need English text?

**Comment by ArithFeather** [comment]
Should support changing language now!

**Comment by Tamago4a** [comment]
Thank. I have refreshed the page with your plugin every 10 minutes.
